### ISSUE TITLE
Yeet not fully yeeting

### ISSUE THREAD

**Issue by PaintNinja** [GroovyMC/APLPKIGB#3]
The compiled language provider jar contains parts of groovy that should be yeeted according to the build.gradle, such as picocli. Yeeting cli-picocli does reduce the filesize slightly, but "groovyjarjar-picocli" remains in the root of the jar.

**Comment by TheSilkMiner** [comment]
It looks like picocli is being shaded into the main Groovy JAR. I assume that this means it's used by some of its internals, so I feel like removing it would be a bit weird and may lead to issues. Is there really no side effect in getting rid of it? Or would it make more sense to shade `cli-picocli` and this point in the language provider too?

**Comment by PaintNinja** [comment]
With Groovy 4 not having an 'all' jar anymore, it might make more sense to just rely on importing individual modules instead imo.

**Comment by PaintNinja** [comment]
Closing as yeet is now just to keep track of which modules are known but not being added
